#!/usr/bin/env bash
# Script that installs Nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www
sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
