#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install nginx -y


echo "Hello World" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com permanent;"
sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart 
