#!/usr/bin/env bash
# diplays the meaasge To infinity and beyond 
# in a indefinite loop before it is killed.
# it also prints a message I am invincible when receving a SIGTERM signal

#Set the trp for SIGTERM
trap "echo 'I'm invincible'" 15

while true;
do
	echo "To infinity and beyond";
	sleep 2
done
