#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
awk '{print $1, $9}' /home/ntahetonyblaise/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/apache-access.log
