#!/usr/bin/env bash
# This script prints best time 10 times but on the nineth time print Hi
str="Best School"
count=1
while [ "$count" -lt 10 ]
do
	if [ "$count" == 9 ];then
		echo "Hi"
	fi
	echo "$str"
	((count++))
done
