#!/usr/bin/env bash
# This script prints best time 10 times but on the nineth time print Hi
count="1"
while [ $count -le 10 ]
do
	echo "Best School"
	if [ $count -eq 9 ]
	then echo "Hi"
	fi
	count=$((count+1))
done
