#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20
count=1
while [ $count -lt 21 ]
do
	echo "$count"

	case $count in
		4)
			echo "bad luck from china"
			;;
		9)
			echo "bad luck from japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((count++))
done
