#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# displays hours from 0 to 12
# display minutes from 1 to 59
h=0
while [ $h -le 12 ]
do
	min=1
	echo "Hour: $h"
	while [ $min -le 59 ]
	do
		echo "$min"
		((min++))
	done
	((h++))
done
