#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# in a list format
# where only the part of the name after the first dash is displayed(refer to the example)
for i in ./;do
	ls
done
