#!/usr/bin/env bash
# script that execute an argument under the user passed as an argument

if [ $# -lt 2 ]; then
  if id "$1" &>/dev/null; then
	 sudo -u "$1" whoami
  else
	  echo "User $1 does not exist."
  fi
fi
